name: MineM-Invoices
version: '${project.version}'
main: nl.rubixstudios.minem.invoices.MineMInvoices
author: PingLagger, Artiquillos
website: https://discord.aizsargs.xyz
api-version: 1.13
depend:
  - Vault
commands:
  invoice:
    description: Manage invoices for players